Setup monitoring (#11)

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -7,7 +7,10 @@ on:
     paths-ignore:
       - '.github/workflows/create_infra.yml'
       - '.github/workflows/destroy_infra.yml'
+      - '.github/workflows/create_monitoring.yml'
+      - '.github/workflows/destroy_monitoring.yml'
       - 'infra/**'
+      - 'monitoring/**'
       - 'README.md'
       - .gitignore
       - 'LICENSE'
@@ -17,7 +20,10 @@ on:
     paths-ignore:
       - '.github/workflows/create_infra.yml'
       - '.github/workflows/destroy_infra.yml'
+      - '.github/workflows/create_monitoring.yml'
+      - '.github/workflows/destroy_monitoring.yml'
       - 'infra/**'
+      - 'monitoring/**'
       - 'README.md'
       - .gitignore
       - 'LICENSE'
@@ -48,17 +54,20 @@ jobs:
           cache: 'maven'
 
       - name: run tests
-        run: mvn clean test
+        run: |
+          cd app
+          mvn clean test
 
       - name: build and scan with sonarqube
         env:
           SONAR_TOKEN: ${{ steps.doppler.outputs.SONARQUBE_TOKEN }}
         run: |
-         mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
-         -Dsonar.java.jdkHome=${{ env.JAVA_HOME }} \
-         -Dsonar.host.url=https://sonarcloud.io \
-         -Dsonar.organization=adewaleopeloyeru \
-         -Dsonar.projectKey=AdewaleOpeloyeru_end-to-end-devops
+          cd app
+          mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
+          -Dsonar.java.jdkHome=${{ env.JAVA_HOME }} \
+          -Dsonar.host.url=https://sonarcloud.io \
+          -Dsonar.organization=adewaleopeloyeru \
+          -Dsonar.projectKey=AdewaleOpeloyeru_end-to-end-devops
 
       - name: setup node.js
         uses: actions/setup-node@v4
@@ -83,7 +92,9 @@ jobs:
         uses: github/codeql-action/analyze@v3
 
       - name: test build docker image
-        run: docker build -t sample-docker-image .
+        run: |
+          cd app
+          docker build -t sample-docker-image .
 
   containerize-and-deliver:
     name: Continuous Delivery
@@ -108,10 +119,14 @@ jobs:
           cache: 'maven'
       
       - name: build with maven
-        run: mvn clean package -DskipTests
+        run: |
+          cd app
+          mvn clean package -DskipTests
 
       - name: build docker image
-        run: docker build -t sample-docker-image .
+        run: |
+          cd app
+          docker build -t sample-docker-image .
 
       - name: tag and push to cloudsmith
         env:
@@ -155,7 +170,9 @@ jobs:
         run: ibmcloud ce
 
       - name: select code engine project
-        run: ibmcloud ce project select --name end_to_end_devops        
+        run: |
+          if ! ibmcloud ce project select --name end_to_end_devops; then
+            echo "project not found, make sure you have created the rquired infrastructure first"        
 
       - name: create registry secret
         env:
